# golangci-lint configuration for claude-tools
# Based on working graphium config: /home/opunix/graphium/.golangci.yml
# Stored in memory database: /home/opunix/claude-memory/project_metadata.db

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  disable:
    - errcheck
    - govet
  enable:
    - staticcheck
    - unused
    - ineffassign
  exclusions:
    paths:
      - vendor
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/evalgo-org/claude-tools
